[versions]
agp = "8.2.0-alpha11"
androidx-activity-activity-compose = "1.7.2"
androidx-activity-compose = "1.7.2"
appcompat = "1.6.1"
coil-compose = "2.3.0"
#core-splashscreen = "1.0.1"
github-XPAY_Android_SDK = "1.0.0"
hilt-android = "2.46"
hilt-navigation-compose = "1.0.0"
kotlin = "1.8.21"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
legacy-support-v4 = "1.0.0"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.00"
firebase-bom = "32.1.0"
google = "4.3.15"
crashlytics = "2.9.4"
material = "1.4.3"
navigation-compose = "2.6.0"
moshi-kotlin = "1.13.0"
okhttp = "5.0.0-alpha.2"
retrofit = "2.9.0"

perf = "1.4.2"
hilt = "2.44"
kapt = "1.8.21"
#ksp = "1.5.21-1.0.0-beta06"
play-services-auth = "20.5.0"
room-runtime = "2.6.0-alpha01"
runtime-livedata = "1.4.3"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
#androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
androidx-appcompat = { group = "androidx.appcompat", name ="appcompat", version.ref = "appcompat" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-legacy-support-v4 = { group = "androidx.legacy" , name ="legacy-support-v4", version.ref = "legacy-support-v4" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-material = { group = "androidx.compose.material" , name = "material", version.ref = "material" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-room-compiler = { group = "androidx.room", name ="room-compiler", version.ref = "room-runtime" }
androidx-room-ktx = { group = "androidx.room" ,name = "room-ktx", version.ref = "room-runtime" }
androidx-room-runtime = { group = "androidx.room", name= "room-runtime", version.ref = "room-runtime" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtime-livedata" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
converter-gson = { group = "com.squareup.retrofit2" , name = "converter-gson", version.ref = "retrofit" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android" }
hilt-compiler = { group = "com.google.dagger" , name = "hilt-compiler", version.ref = "hilt-android" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }

play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
pustovitandriy-XPAY_Android_SDK = { group = "com.github.pustovitandriy", name= "XPAY_Android_SDK", version.ref = "github-XPAY_Android_SDK" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-kotlin" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
perf = { id = "com.google.firebase.firebase-perf", version.ref = "perf" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kapt" }
#ksp = {id = "com.google.devtools.ksp" ,version.ref = "ksp" }

[bundles]

